### ISSUE TITLE
Not working since updated to .NET 6.

### ISSUE THREAD

**Issue by mhosman** [efcore/EFCore.NamingConventions#102]
`System.TypeLoadException: 'Method 'GetServiceProviderHashCode' in type 'ExtensionInfo' from assembly 'EFCore.NamingConventions, Version=5.0.2.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7' does not have an implementation.'`

**Comment by roji** [comment]
I'll be releasing a 6.0.0 version of this package very soon, that will be cmopatible with EF Core 6.0.
