### ISSUE TITLE
The repository primary key has expired

### ISSUE THREAD

**Issue by douglas-wiliam** [efcore/EFCore.NamingConventions#106]
Hi everyone!

I get this error when I try to install the package via .NET CLI:

Error NU3028: Package 'EFCore.NamingConventions 5.0.2' from source 'https://api.nuget.org/v3/index.json': The repository primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
/path_to_my_project : error NU3037: Package 'EFCore.NamingConventions 5.0.2' from source 'https://api.nuget.org/v3/index.json': The repository primary signature validity period has expired.
 Failed to restore

**Comment by roji** [comment]
@douglas-wiliam this is very unlikely to be related to Npgsql itself - take a look at [this issue](https://github.com/dotnet/core/issues/6595), for example (specifically try upgrading to the very latest SDK, etc.
