### ISSUE TITLE
Not compatible with .NET 6.0

### ISSUE THREAD

**Issue by odinnou** [efcore/EFCore.NamingConventions#108]
Hello!
First of all, thank you for your job.
It's the early adoption of .NET 6 that brings me here ^^.

**All my tests fall in failure because of that exception:** 

> System.TypeLoadException : Method 'GetServiceProviderHashCode' in type 'ExtensionInfo' from assembly 'EFCore.NamingConventions, Version=5.0.2.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7' does not have an implementation.

It occurs when this line is called : 

```
services.AddDbContext<BakerContext>(options => options.UseLazyLoadingProxies().UseNpgsql(appSettings.DbConnection).UseSnakeCaseNamingConvention());
```

Thanks in advance, kind regards

PS: maybe you already know about it and in that case sorry ^^.

**Comment by nicolaiarocci** [comment]
Hello, I had the same issue. Installing EFCore.NamingConventions 6.0.0-rc.1 solved the problem (at the cost of a build warning because I'm running a prerelease under a stable release). Hopefully EFCore.NamingConvetions 6 will be released soon.

**Comment by nicolaiarocci** [comment]
Also see #92

**Comment by odinnou** [comment]
Oh sorry, I didn't check if a pre-release version exists :( my bad!

**Comment by roji** [comment]
A 6.0.0 version will be published very soon.
