### ISSUE TITLE
[EF 6.0] Method 'GetServiceProviderHashCode' in type 'ExtensionInfo' from assembly 'EFCore.NamingConventions, Version=5.0.2.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7' does not have an implementation.

### ISSUE THREAD

**Issue by yunfandev** [efcore/EFCore.NamingConventions#110]
After upgrade to EF Core 6.0 when try to add migration the following error occurred
`
An error occurred while accessing the Microsoft.Extensions.Hosting services. Continuing without the application service provider. Error: Method 'GetServiceProviderHashCode' in type 'ExtensionInfo' from assembly 'EFCore.NamingConventions, Version=5.0.2.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7' does not have an implementation.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeLoadException: Method 'GetServiceProviderHashCode' in type 'ExtensionInfo' from assembly 'EFCore.NamingConventions, Version=5.0.2.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7' does not have an implementation.
   at EFCore.NamingConventions.Internal.NamingConventionsOptionsExtension.get_Info()
`

**Comment by tonikinni** [comment]
I got the same problem. Have to check `Include prerelease` -checkbox in package manager and use `6.0.0-rc.1` until `6.0.0` version becomes available.

**Comment by roji** [comment]
6.0.0 will be out soon.
