### ISSUE TITLE
UseLowerCaseNamingConvention results in wrong casing for Owned Entity Columns

### ISSUE THREAD

**Issue by groogiam** [efcore/EFCore.NamingConventions#121]
When using `ctx.Database.EnsureCreated()` owned entity columns are created without the convention.

```csharp

//configure services options
options.UseNpgsql(connectionString).UseLowerCaseNamingConvention();

//entity configuration
            //configure EntitySummaryConfigScript template script
            builder.OwnsOne(o => o.Script, sa =>
            {
                sa.Property(p => p.ScriptName).HasColumnName("ScriptName");
                sa.Property(p => p.Usings).HasColumnName("ScriptUsings");
                sa.Property(p => p.TemplateStart).HasColumnName("ScriptStart");
                sa.Property(p => p.ScriptContent).HasColumnName("ScriptContent");
                sa.Property(p => p.TemplateEnd).HasColumnName("ScriptEnd");
            });

```

Results in the following casing of the created database schema.

![image](https://user-images.githubusercontent.com/1992395/151615741-b642d6bb-7d7d-4158-9f80-666d4f353f86.png)

**Comment by roji** [comment]
@groogiam when you specify column names explicitly via HasColumnName(), those aren't overridden by this plugin. This plugin merely provides default conventions which apply for column/tables where the name isn't explicitly configured.
