### ISSUE TITLE
Properties using HasColumnName not translated

### ISSUE THREAD

**Issue by JonasBRasmussen** [efcore/EFCore.NamingConventions#125]
In a project of mine we have a table-per-hierarchy with a base type, where we reuse the same column among several derived types. Thus we have to specify the column name in the entity configuration with `HasColumnName("MyColumn")` as described in https://docs.microsoft.com/en-us/ef/core/modeling/inheritance#shared-columns. When generating a new migration this column is not generated with whatever naming convention that is configured, e.g., `my_column` for snake case.

In general it seems like properties that explicitly use `HasColumnName` are not generated with the configured naming convention, but always remains the exact string specified. Is this a limitation of this project or of EF Core in general? Is there anything I can do to fix this?

We generate migrations for several database providers from the same entity configurations and are very happy to use this package to generate DB-specific names.

**Comment by roji** [comment]
This is by-design: this plugin adds a convention which does not override user-set defaults. If we did that, it would be impossible for users to explicitly set any column names anywhere, since the convention would always have precedence. For cases where you're specifying column names explicitly, you'll have to apply the naming convention yourself (i.e. `HasColumnName("my_column")`.

**Comment by JonasBRasmussen** [comment]
But `my_column` is a DB provider specific name for the column. We can't set that in the entity configuration since it would then cause the wrong naming for the database which should have the column name `MyColumn` or `myColumn`.

**Comment by roji** [comment]
If you're using multiple providers, you can set the name only for PostgreSQL by using the following in OnModelCreating:

```c#
if (Database.IsNpgsql())
{
   ...
}
```

**Comment by JonasBRasmussen** [comment]
I'm closing this. For anyone interested, I created a custom `ModelBuilder` extension method, to convert any names not converted by this library.

**Comment by saber-wang** [comment]
@JonasBRasmussen  Can you share it?
