### ISSUE TITLE
Calling withoutnaming will throw an exception

### ISSUE THREAD

**Issue by saber-wang** [efcore/EFCore.NamingConventions#137]
https://github.com/efcore/EFCore.NamingConventions/blob/560803ee57434a5987355605ba6b833d64da2d16/EFCore.NamingConventions/Internal/NamingConventionsOptionsExtension.cs#L31

exception:
https://github.com/efcore/EFCore.NamingConventions/blob/560803ee57434a5987355605ba6b833d64da2d16/EFCore.NamingConventions/Internal/NamingConventionsOptionsExtension.cs#L109

**Comment by roji** [comment]
Fixed as part of #243
