### ISSUE TITLE
Index Convention problem

### ISSUE THREAD

**Issue by gemoglobin** [efcore/EFCore.NamingConventions#145]
For example i have: entity.HasIndex(e => e.Name, );
after migration I get: "ix_organization_name_index".

I think the problem is: public void ProcessIndexAdded(
         IConventionIndexBuilder indexBuilder,
         IConventionContext<IConventionIndexBuilder> context)
         => indexBuilder.HasDatabaseName(_namingNameRewriter.RewriteName(indexBuilder.Metadata.GetDefaultDatabaseName));

Maybe you need to change .GetDefaultDatabaseName() to Name

**Comment by roji** [comment]
Sorry for not looking at this sooner.

It isn't clear what the problem with the name is - the index name above seems to be snake-cased properly. As always, it's better to include a minimal code repro that shows exactly what's being done, along with the expectation.

As this has been open for a long while, I'll go ahead and close it; but if there's interest in this, please post the additional details to make this clearer and I'll reopen.
