### ISSUE TITLE
Generated designer file with derived type fails to compile when schema specified

### ISSUE THREAD

**Issue by jasonmueller** [efcore/EFCore.NamingConventions#16]
When using any of the included conventions with a base type and derived type and a non-default schema, the designer file generated by `dotnet ef migrations add` fails to build.  I'm using version 3.1.1 dependencies for tooling and packages and .NET Core 3.1.

This appears to be happening in the EF Core stack somewhere, after conventions are applied, but I can't tell for sure.  It looks like it's trying to write to the designer file manually rather than using some code generator because the syntax of the file is invalid.

I've included a repro solution, along with migration files, for a number of cases which can be compared to see the differences between scenarios. 

[Repro solution and instructions](https://github.com/jasonmueller/EFCore.NamingConventions.Repro)

When no schema is specified, [this file](https://github.com/jasonmueller/EFCore.NamingConventions.Repro/blob/master/Data/Migrations/20200207161734___WithConventions_NoSchema.Designer.cs) (which build successfully) is generated.

When a schema is specified, [this file](https://github.com/jasonmueller/EFCore.NamingConventions.Repro/blob/master/Data/Migrations/20200207164417___WithOriginalConventions_WithSchema.Designer.cs) (which does not build, due to this [offending line](https://github.com/jasonmueller/EFCore.NamingConventions.Repro/blob/b5597b7ffc2e98cedee58b6dac79a7f2d4583406/Data/Migrations/20200207164417___WithOriginalConventions_WithSchema.Designer.cs#L52)) is generated.

When a schema is specified with my "fix", below, [this file](https://github.com/jasonmueller/EFCore.NamingConventions.Repro/blob/master/Data/Migrations/20200207162056___WithTweakedConventions_WithSchema.Designer.cs) (which builds successfully) is generated.

In order to "fix" the problem, I made the following change to `NameRewriterBase.cs`:

```cs
        public virtual void ProcessEntityTypeAdded(
            IConventionEntityTypeBuilder entityTypeBuilder, IConventionContext<IConventionEntityTypeBuilder> context)
            => entityTypeBuilder.ToTable(
                RewriteName(entityTypeBuilder.Metadata.GetTableName()),
                entityTypeBuilder.Metadata.GetSchema());
```

==>

```cs
        public virtual void ProcessEntityTypeAdded(
            IConventionEntityTypeBuilder entityTypeBuilder, IConventionContext<IConventionEntityTypeBuilder> context)
            => entityTypeBuilder.ToTable(
                RewriteName(entityTypeBuilder.Metadata.GetTableName()),
                null);
```

I could open a PR with my "fix", but I don't know what the implications are since these interfaces in the EF stack are new to me.  Also, I'm sure(?) this will break something when EF introduces TPC or TPT for inheritance.

**Comment by roji** [comment]
@jasonmueller thanks for reporting this, and the quality repro/workaround suggestions (and sorry it has taken me so long to get around to it). The basic problem here is that the plugin attempts to rename derived types, which makes no sense in the current EF Core inheritance support (which is TPH only). When 5.0 is released with TPT, we'd need to support that (opened #29 to track).
