### ISSUE TITLE
EFCore.NamingConventions causing EF Core 7 Json Column OwnsMany() throw Sequence contains no elements exception

### ISSUE THREAD

**Issue by jia-ming-li-rs** [efcore/EFCore.NamingConventions#173]
Hi @roji 

EFCore.NamingConventions causing EF Core 7 Json Column `OwnsMany` thows `System.InvalidOperationException: Sequence contains no elements`

```        public void Configure(EntityTypeBuilder<Employee> builder)
        {
            builder.ToTable(nameof(Employee));

            builder.HasKey(x => x.Id);
            builder.Property(x => x.Id).UseIdentityColumn(100);
            builder.Property(x => x.FullName).HasMaxLength(255);

            builder.OwnsOne(x => x.ContactDetail, y =>
            {
                y.ToJson();
                y.OwnsOne(z => z.Contact);
                y.OwnsMany(z => z.Addresses); //NamingConventions causing this throws Sequence contains no elements exception
            });
        }
```

```
Build started...
Build succeeded.
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.ValidateJsonEntities(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)   at Microsoft.EntityFrameworkCore.SqlServer.Infrastructure.Internal.SqlServerModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
```

**Comment by alonafish** [comment]
I also had this issue. The extension does not lower the name of sequence

**Comment by JarrodJ83** [comment]
I'm using v7.0.2 and still seeing this issue. Should it be fixed in this version?

**Comment by balloman** [comment]
Is this issue actually fixed? I'm still encountering it

**Comment by jia-ming-li-rs** [comment]
@balloman , it works, but you have to have a root element to wrap the list. 

for example.

`    public void Configure(EntityTypeBuilder<ReportInstance> builder)
    {
        builder.ToTable(nameof(Domain.Entities.ReportInstance).ToUnderscoreCase()!, AssetMgmtDbContext.SchemaAssetMgmt);

        builder.Property(x => x.Name).HasMaxLength(128);
        builder.Property(x => x.ClientId);
        //...
        
        //OwnsOne
        builder.OwnsOne(
            x => x.QueryParameter,
            y =>
            {
                y.ToJson("query_parameter");
                y.OwnsMany(z => z.ClientIds);
                y.OwnsMany(z => z.FundIds);
                y.OwnsMany(z => z.FundCodes);
                y.OwnsMany(z => z.LegalEntityNames);
                y.OwnsMany(z => z.States);
                y.OwnsMany(z => z.Markets);
                y.OwnsMany(z => z.UnitCodes);
            });
      }
} 
`
