### ISSUE TITLE
Override explicit column names to use naming convention

### ISSUE THREAD

**Issue by mehdihadeli** [efcore/EFCore.NamingConventions#175]
Hi,
Could we override explicit column names in fluent configuration of ef core with `snake case` naming convention?

``` csharp
  builder.Property(x => x.PhoneNumber).HasColumnName("PhoneNumber")
```
I expect after setting `UseSnakeCaseNamingConvention()`, it overrides this column name to use convention, but in database it is `PhoneNumber`.

**Comment by roji** [comment]
Explicit configuration via the Fluent API always overrides conventions, so yeah - that's expected.
