### ISSUE TITLE
The applied extension does not affect the generated script

### ISSUE THREAD

**Issue by alexandis** [efcore/EFCore.NamingConventions#186]
I'm trying to apply the extension like this:

```
    public class CentralToolsMigrationsDbContextFactory : IDesignTimeDbContextFactory<CentralToolsMigrationsDbContext>
    {
        public CentralToolsMigrationsDbContext CreateDbContext(string[] args)
        {
            CentralToolsEfCoreEntityExtensionMappings.Configure();

            var configuration = BuildConfiguration();

            var builder = new DbContextOptionsBuilder<CentralToolsMigrationsDbContext>()
                .UseOracle
                (
                    configuration.GetConnectionString("Default"),
                    x => x.MigrationsHistoryTable("EFMIGRATIONSHISTORY__", CentralToolsConsts.DbSchema)
                )
                .UseUpperCaseNamingConvention()
                .ReplaceService<IHistoryRepository, CentralToolsMigrationHistoryRepository>();

            return new CentralToolsMigrationsDbContext(builder.Options);
        }

        private static IConfigurationRoot BuildConfiguration()
        {
            var builder = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("appsettings.json", optional: false);

            return builder.Build();
        }
    }
```

I run `Add-Migration`, then - `Script-Migration` from _Package Manager Console_, but looks like there is no trace of the extension, the case for tables / columns / indexes is what it was before, in some cases it is uppercase, in some cases it is camel...
What is going on? I don't get it? I thought that everything will be in uppercase now:

![image](https://user-images.githubusercontent.com/6149843/219984162-f2e1fbe3-f8f2-4dab-b31f-d41b4b121ad6.png)

I don't know if such generation is the reason, but these `CREATE` commands are not supposed to be here at all: by default Oracle creates everything in uppercase, no matter what was the input. So I already have all these tables in DB and the script is incorrect. Devart resolved this issue by configured option to disable quotes. Unfortunately, it is not up-to-date with NET7, so I hoped I would be able to complete the migration with this extension...

Honestly - it would be much easier just to allow removing the quotes for Oracle: it would resolve the problems in many scenarios ;)

**Comment by roji** [comment]
Are you saying that some tables do get upper-cased, but others no? If that's the case, then there's likely some place in the code somewhere which explicitly sets the naming for the tables not getting upper-cased (this plugin's convention only affects names which aren't explicitly set).

> [...] by default Oracle creates everything in uppercase, no matter what was the input. So I already have all these tables in DB and the script is incorrect. Devart resolved this issue by configured option to disable quotes.

Wouldn't this break if you happened to have two .NET properties with names differing only by their case? In any case, if this is something you want to do, you can replace the Oracle's ISqlGenerationHelper and change the behavior to not emit quotes.

**Comment by alexandis** [comment]
@roji thank you for the reply. Regarding the first part - ok, clear now. Regarding the second one - yes, I understand the risks, but at least wild be great to have the option to take the responsibility and change the generation behavior. So thank you for the advice with `ISqlGenerationHelper`, will have a look at it.

**Comment by alexandis** [comment]
Sorry for bothering you again, @roji 
`ISqlGenerationHelper` helped me to deal with quotations and case register. But probably you kno how to deal with case here?

![image](https://user-images.githubusercontent.com/6149843/220123575-5d63f376-3a25-4a70-bde3-ed548f8a01e8.png)

**Comment by roji** [comment]
Not sure exactly what you're asking - are you using EFCore.NamingConventions or not?

**Comment by alexandis** [comment]
At least I've tried to:

![image](https://user-images.githubusercontent.com/6149843/220126283-0022b3b5-48c9-4acb-a6fd-aa6453851d84.png)

However as seen from the screen the table and column names referenced in the system table SELECT are in camel-case. But I have all the tables and column names in my Oracle DB in upper-case, this has been done automatically when these tables have been created (despite the case which was declared by the earlier generated migration script).

Now I'm trying to force everything in my current script to be upper-cased, including those references. I'm not sure your extension can deal with such as you described in your previous message. But I need to do it somehow.. Preferrably automatically, by overriding the class similar to `OracleSqlGenerationHelper`...

**Comment by roji** [comment]
> However as seen from the previous screenshot, the table and column names referenced in the system table SELECT are in camel-case

If you're doing UseUpperCaseNamingConvention, all identifiers should be upper-cased for you - if not that's a bug, and that's what we should probably concentrate on... Are all identifiers (table/column names) camel-case?

**Comment by alexandis** [comment]
I think this is a normal behavior of the plugin. The fact is that I can't resolve my problem with it. We use 3rd part framework and the creator set his table names in camel case. But our client demanded the DB setting which causes all DB entities to be created in uppercase. So what I need is to make a migration script generate everything in uppercase - no matter what are the explicit settings for naming...

**Comment by roji** [comment]
OK. If identifiers are being explicitly set, this plugin indeed cannot do anything to them. At that point your only option is to either set them manually yourself, or perform the upper-casing yourself in SqlGeneratorHelper.DelimitIdentifier/EscapeIdentifier (note that there are several overloads there).

**Comment by alexandis** [comment]
I see. Ok. Thank you for clarification. I uppercased the entities names using the Helper, but it didn't affect the names in SELECT from system tables on screenshot. That's why I thought it needs another way.. Probably I need to take a more careful look at the Helper. Or just "postprocess" the script manually with Regex in Notepad++ :)

**Comment by roji** [comment]
Yeah, that query doesn't render SQL identifiers - the table/column names are rendered as text inside the queries, and so it doesn't go through the SQL generation helper (that's also why there are no quotes - they're not identifiers). For that case there's nothing you can do within EF Core, AFAIK.
