### ISSUE TITLE
Globalization mistake

### ISSUE THREAD

**Issue by emrahcetiner** [efcore/EFCore.NamingConventions#19]
"ID" converting to "ıd" with tr-TR globalization.
should be define default thread culture to en-us or may be UseSnakeCaseNamingConvention take culture parameter.

**Comment by roji** [comment]
Thanks - make sense. If you'd like to do a PR I'd be happy to look at it (the plugin really isn't very complicated).

**Comment by adomorn** [comment]
just use Invariant version of ToLower method

**Comment by roji** [comment]
We should definitely accept a culture parameter to the extension methods, and default to Invariant. I'd welcome a PR on this.

**Comment by adomorn** [comment]
PR sent :)

**Comment by kad1r** [comment]
I'm still having the same issue. How can I fix it?

**Comment by roji** [comment]
This has been fixed for version 5.0.0 - you can try the released 5.0.0-preview5 (but will have to align to preview5 with other EF Core-related packages).
