### ISSUE TITLE
Apply naming conventions on EF 8 FromSql unmapped types

### ISSUE THREAD

**Issue by veikkoeeva** [efcore/EFCore.NamingConventions#197]
Would it be possible to use this with the new EF 8 unmapped types with `.SqlQuery` for both mapped and unmapped types? I think it would be helpful to even just have an option to force attribute names to be case insensitive.

It looks to me this is not possible, so perhaps this issues serves as a note that it'd be helpful to have a way to control attribute name mapping case, maybe also type mapping (e.g. from snake_case to PascalCase).

**Comment by roji** [comment]
SqlQuery executes user-provided SQL against the database, returning scalar values - since the SQL is provided by the user, it's the user's responsibility to reference the right table and column names... What is it that you think EFCore.NamingConvention could be doing here?

**Comment by veikkoeeva** [comment]
I realize I could have written example code to be clearer. Let I start with that before answering to your question.

Let's define a table like

```
create table if not exists SomeTable
(
   Id serial primary key,
   UserId text not null,
   Version timestamp(6) default current_timestamp
);
```

Then in code
```
public class Some
{
   public int Id { get; set; }
   public string UserId { get; set; }
   public DateTime Version { get; set; }
}
```

One could query it like `var somes = await DbContextDerived.Database.SqlQuery<Some>($"""select id AS "Id", userid AS "UserId", version as "Version from sometable""""`).FirstOrDefaultAsync();`

I was thinking that it could be useful if it were possible to define this matching between `public class Some` attributes and `SomeTable` column names with something like `IgnoreCase` or `CamelCase`. I could imagine it would go to `DbContextDerived: DbContext`, but somehow I could make it succeed and assume(d) it's not possible either in EF directly or using this library.

As for your note about user provided SQL, it actually already was useful. I realized I could rename the columns in the query and that is useful. So my initial question was a bit silly considering my problem (maybe I ought to go to sleep indeed), but an option like that is what I was thinking. It looks to me it works only for the defined DTO mappings and not for unmapped types.

**Comment by roji** [comment]
> I was thinking that it could be useful if it were possible to define this matching between public class Some attributes and SomeTable column names with something like IgnoreCase or CamelCase.

Applying CamelCase (or snake_case, or other cases) is exactly what this plugin is for (EFCore.NamingConventions) - you configure it once on your DbContext, and it makes all table and column names adhere to your desired casing. Or am I misunderstanding?

IgnoreCase doesn't work here, since that's not a naming scheme - it's you asking the database to behave in a different way, namely to ignore case when looking up table/column names.

So I'm still not sure if there's something that's not already implemented that you're proposing.

**Comment by veikkoeeva** [comment]
I was thinking I could write the query like `DbContextDerived.Database.SqlQuery<Some>("select id, userid, version from sometable")` and have it mapped to CamelCase DTO attributes in the unmapped POCO that is not defined in the `DbContextDerived: DbContext`. If it should work, I have made a mistake somehow. I need to recheck.

**Comment by roji** [comment]
If you're using EFCore.NamingConventions with the snake_case convention, then your CamelCase DTO properties (e.g. SomeProperty) should get mapped to snake_case columns in the database (some_property). At that point you can query them above with `id`, no?

**Comment by veikkoeeva** [comment]
It does work. It was my bad somehow I managed to pull of and then double pull-off. I thank you for the patience and kindness.
