### ISSUE TITLE
Not making any changes to table names, but does columns

### ISSUE THREAD

**Issue by 10GeekJames** [efcore/EFCore.NamingConventions#21]

**Comment by 10GeekJames** [comment]
![image](https://user-images.githubusercontent.com/5634551/79055267-b3282280-7c19-11ea-8c1f-b75dae94701d.png)

**Comment by roji** [comment]
Duplicate of #2

**Comment by roji** [comment]
This is a problem specific to ASP.NET Identity. Note that you can use the workaround detailed here: https://github.com/efcore/EFCore.NamingConventions/issues/2#issuecomment-612651161
