### ISSUE TITLE
.Net8 support 

### ISSUE THREAD

**Issue by dmitriyi-affinity** [efcore/EFCore.NamingConventions#216]
.Net/EFCore 8.0 RC1 has been released. Please add support.

**Comment by joseftw** [comment]
See https://github.com/efcore/EFCore.NamingConventions/issues/209

**Comment by mhosman** [comment]
I think with RC1 we have a good opporunity to start testing .NET 8. I'm trying to migrate my project but I get an error so I need to rollback to .NET 7.

**Comment by mendozagit** [comment]
.NET8 will bensuported?

**Comment by roji** [comment]
Yes, but closer to the release - I'm far too busy with other things at the moment.

**Comment by mendozagit** [comment]
Thanks @roji

**Comment by nmarkezic** [comment]
@roji any ETA for .NET core 8 support?

**Comment by bricelam** [comment]
Working on this now. Hoping to have a prerelease out in a few days.

**Comment by roji** [comment]
Thanks @bricelam! Just pushed 8.0.0-rc.2 to nuget.org.

**Comment by joseftw** [comment]
Works perfectly, THANK YOU

**Comment by inghamc-csu** [comment]
+100 for this, and releasing in the wee hours of a Saturday morning - you
guys are heros ***@***.*** <https://github.com/bricelam>, @roji
<https://github.com/roji>, many others)
