### ISSUE TITLE
UseInternalServiceProvider

### ISSUE THREAD

**Issue by FoxTes** [efcore/EFCore.NamingConventions#219]
Using `UseInternalServiceProvider()` I get incorrect behavior of this library. It just stops working.

`UseInternalServiceProvider()` is required for the factory when creating the migration. Can you tell me how you can work around this problem? 

I have already seen PR on this topic before, but there is no solution there.

```
public class ApplicationContextFactory : IDesignTimeDbContextFactory<ApplicationContext>, IAsyncDisposable
{
    private readonly NpgsqlDataSource _dataSource;
    private readonly IServiceProvider _serviceProvider;

    public ApplicationContextFactory()
    {
        var builder = WebApplication.CreateBuilder(Array.Empty<string>());
        var connectionString = builder.Configuration.GetConnectionString(nameof(ApplicationContext));
        
        builder.Services
            .AddEntityFrameworkNpgsql()
            .AddEntityFrameworkNamingConventions();
        
        var dataSourceBuilder = new NpgsqlDataSourceBuilder(connectionString);
        
        _dataSource = dataSourceBuilder.Build();
        _serviceProvider = builder.Build().Services;
    }

    public ApplicationContext CreateDbContext(string[] args)
    {
        var optionsBuilder = new DbContextOptionsBuilder<ApplicationContext>();
        optionsBuilder
            .UseNpgsql(_dataSource)
            .UseSnakeCaseNamingConvention()
            .UseInternalServiceProvider(_serviceProvider);

        return new ApplicationContext(optionsBuilder.Options);
    }
    
    public ValueTask DisposeAsync()=> _dataSource.DisposeAsync();
}
```

**Comment by FoxTes** [comment]
@Azmond have you solved this problem?

**Comment by roji** [comment]
@FoxTes you should in almost all cases not be using UseInternalServiceProvider in a normal app - any particular reason you're doing that?

**Comment by FoxTes** [comment]
@roji 
I use `UseInternalServiceProvider()` only in `IDesignTimeDbContextFactory`.

I need to get in the context of `IOptions` (and maybe other servicies) for the `OnModelCreating()` method.

In the application itself, DI solves this problem.

Is it possible to solve the problem with migrations and `IDesignTimeDbContextFactory`?

**Comment by FoxTes** [comment]
Well, I solved the problem not in the most obvious way :)

```
public class ApplicationContextFactory : IDesignTimeDbContextFactory<ApplicationContext>
{
    private readonly IServiceProvider _serviceProvider;

    public ApplicationContextFactory()
    {
        var builder = WebApplication.CreateBuilder(Array.Empty<string>())
            .AddOptions()
            .AddDbContextFactoryServices();
        
        var dataSourceBuilder = new NpgsqlDataSourceBuilder(
            builder.Configuration.GetConnectionString(nameof(ApplicationContext)));
        dataSourceBuilder.MapEnum<ActionType>();
        dataSourceBuilder.MapEnum<WorkoutType>();
        
        builder.Services.AddDbContext<ApplicationContext>(
            options => options
                .UseNpgsql(dataSourceBuilder.Build(), option => option.UseNodaTime())
                .UseSnakeCaseNamingConvention(), 
            ServiceLifetime.Singleton);
        
        _serviceProvider = builder.Build().Services;
    }

    public ApplicationContext CreateDbContext(string[] args) =>
        _serviceProvider.GetRequiredService<ApplicationContext>();
}
```

**Comment by roji** [comment]
@FoxTes great that you could get rid of UseInternalServiceProvider(). If you're simply looking for the design-time context to be the same thing that your application sets up in WebApplication, you maybe don't need to define a IDesignTimeDbContextFactory at all - [see the docs](https://learn.microsoft.com/en-us/ef/core/cli/dbcontext-creation?tabs=dotnet-core-cli#from-application-services).

In any case, I'll go ahead and close this as the problem seems to be solved.

**Comment by FoxTes** [comment]
_[ASP.NET Core Web Host](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host) or [.NET Core Generic Host](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host)_

In my case, `WebApplication` is used and therefore this is not suitable for me

**Comment by FoxTes** [comment]
Yeap, it's worked! Thanks for the hint

**Comment by roji** [comment]
Great!
