### ISSUE TITLE
Problem with table names

### ISSUE THREAD

**Issue by mhosman** [efcore/EFCore.NamingConventions#22]
Columns are being updated to snake case but table names remain unchanged

**Comment by iSlaffko** [comment]
You've probably used implicit table naming, e.g. .ToTable("TableName") which is not a convention naming but rather an implicit one. Should you eliminate such statement and create new migration, related table will probably be renamed according to the used convention.

**Comment by roji** [comment]
In addition to what @iSlaffko wrote, the plugin cannot manage the naming of ASP.NET Identity tables (as opposed to their columns), see #2.

Otherwise can you please post a short code sample to show the problem?

**Comment by mhosman** [comment]
Okay yes, I'm using implicit table naming: .ToTable("whatever"). I'll change that.
Closing issue. Thanks!!
