### ISSUE TITLE
.NET 8 nuget release

### ISSUE THREAD

**Issue by lilinus** [efcore/EFCore.NamingConventions#230]
Hi, I see changes for .NET 8 are merged and .NET RC2 is supported in latest nuget. When will .NET 8 GA support be available as a nuget package version?

**Comment by roji** [comment]
Soon.

**Comment by mendozagit** [comment]
Thanks @roji

**Comment by botrot** [comment]
Hi guys, where do you see that rc.2, there is one from 2022 but I believe that's not the one you are talking about.

**Comment by botrot** [comment]
nvm found it

**Comment by RuslanMonar** [comment]
any news?

**Comment by roji** [comment]
Still too busy with post-8.0 bug fixes and urgent tasks, please use rc.2 in the time being.

**Comment by RuslanMonar** [comment]
I'm sorry to bother you, but can you tell me approximately when the library update will be?
Because this is the only library that blocks migration to .NET 8 and I would like to know if we will be in time for the release of our project

**Comment by md-redwan-hossain** [comment]
Any update for the new release? Migration to dotnet 8 is halted for me too for this library.

**Comment by georg-jung** [comment]
Maybe you're already aware, but might be interesting to note that there are more options than just waiting:

* Go all in on 8.0 now and get everything else ready and use `rc2` of this package for the time beeing.
* Upgrade runtime and aspnetcore etc. to 8.0, but stick with ef core 7.0 for now. I did this for one project as this package wasn't the only one which didn't (fully/GA) support 8.0 yet. You can start using many of the 8.0 benefits regarding runtime/aspnetcore earlier and get started with the transition related work that way.

**Comment by RzNmKX** [comment]
Any ETA on the 8.0 release?

**Comment by roji** [comment]
Almost there, should be released in the next couple of weeks.

**Comment by roji** [comment]
Everyone, 8.0.0 has just been released and is available on nuget.org; thank you for your patience. I did a big push to resolve as many bugs as I could - hopefully this plugin now works with many more modeling scenarios.
