### ISSUE TITLE
The object has been removed from the model.

### ISSUE THREAD

**Issue by nicpot** [efcore/EFCore.NamingConventions#250]
I have an EFCore 8.0 console testing app in which I use the  `UseSnakeCaseNamingConvention()` option on a postgresql dbContext with` UseNpgsl()` for testing and designing some entities . I have a  `await db.Database.EnsureDeletedAsync(cancellationToken)` and `await db.Database.EnsureCreatedAsync(cancellationToken)`  and both throws with 'The object has been removed from the model.' once I upgraded EFCore.NamingConventions to 8.0.0 and even 8.0.1.  

I have had no such issues with 8.0.0-rc2, and I have now rolled back to 8.0.0-rc2 and it works 100% like before the updates.

Thanks for the  package btw!

**Comment by roji** [comment]
Duplicate of #251

**Comment by roji** [comment]
Can you please try to put together a minimal repro and post it to #251? If that's done I can investigate and fix if necessary.
