### ISSUE TITLE
Apply more than one convention or create a new one

### ISSUE THREAD

**Issue by rafaelpadovezi** [efcore/EFCore.NamingConventions#31]
One useful convention is the UPPER_CASE combined with snake_case. I did a quick test and it seems using more than one convention does not work.

I could try to make a PR if you don't mind, but what would be the best way?

**Comment by roji** [comment]
Yeah, you can't combine naming conventions - and I don't think it would be a good idea to go down this route (things are a bit more complex than they seem). However, we could just add a new convention called UpperSnakeCase, which should be rather trivial...

**Comment by roji** [comment]
Thanks @rafaelpadovezi, merged you PR!

**Comment by rafaelpadovezi** [comment]
Thanks @roji. Will you release a new nuget version soon?

**Comment by roji** [comment]
If you're on the EF Core 5.0 previews, then I'll probably release a nuget here very soon, for preview6. Apart from that, I wasn't planning on another release for 3.1 - the master branch has already been modified to work with the latest EF Core 5.0, so backporting this for 3.1 isn't completely trivial. Is using 5.0 previews an option for you? They're considered quite stable.

**Comment by rafaelpadovezi** [comment]
It's not an option because I'm using EF with Oracle. Using this package would give me a better and more robust solution but I can wait if Oracle don't delay their release forever. Thank you for your time.

**Comment by tharasompan** [comment]
> Yeah, you can't combine naming conventions - and I don't think it would be a good idea to go down this route (things are a bit more complex than they seem). However, we could just add a new convention called UpperSnakeCase, which should be rather trivial...

I found that the entity with [Owned] attribute is not converted when I use UpperSnakeCase.
For example:-
[Owned]
public class RefreshToken
{ ... }

Table name "RefreshToken" is created instead of "REFRESH_TOKEN".

**Comment by roji** [comment]
@tharasompan can you please open a new issue with a full model?

**Comment by tharasompan** [comment]
Hi,

I found that it’s opened with issue
Snake case naming convention does not applied to owned types #69

Best regards,
Thara Sompan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
