### ISSUE TITLE
When using Owned entity types, UseSnakeCaseNamingConvention will split tables

### ISSUE THREAD

**Issue by alaatm** [efcore/EFCore.NamingConventions#4]
When using `OwnsOne(...)`, the owned entity will be created in its own table and a shadow PK/FK is created.

This is a different behaviour from the default where the owned entity should be mapped to the parent table instead.

```cs
public class Blog
{
    public int Id { get; set; }
    public BlogStatistics Statistics { get; set; }
}

public class BlogStatistics
{
    public string Name { get; set; }
}

modelBuilder.Entity<Blog>().OwnsOne(p => p.Statistics);
```

With `UseSnakeCaseNamingConvention()` the following tables are created:

```
blogs (id PK)
blog_statistics (blog_id PK FK, name)
```

**Without** `UseSnakeCaseNamingConvention()` the following table is created:

```
Blogs (Id PK, Statistics_Name)
```

**Comment by roji** [comment]
Apologies, I was accidentally not subscribed to notifications on this repo, will try to investigate ASAP.

**Comment by devgrav** [comment]
Hello, @roji! Do you have any news about this issue?

**Comment by roji** [comment]
No, sorry, I haven't had time to look... I'll try to find time next week to look at this.

**Comment by jamalabo1** [comment]
@roji This issue is still happening even in version `1.1.0`

**Comment by roji** [comment]
@jamalabo1 can you please open a new issue for this? I'll look into it.
