### ISSUE TITLE
Question : can I use v5.0.0-rc1 with EF Core 5.0.0 release ?

### ISSUE THREAD

**Issue by odinnou** [efcore/EFCore.NamingConventions#44]
Hello, first of all thank for your amazing job.

I have an early adopter question :P
.NET 5.0 was just released a week ago, the 5.0.0-rc1 version of "NamingConventions" is it fully compatible with EF Core 5.0.0 or I need to wait a little bit for the true release ?

Thanks in advance,
Kind regards

**Comment by roji** [comment]
It *may* work, but it would be more advisable to wait another week or two until a 5.0.0 version of EFCore.NamingConventions is released.
