### ISSUE TITLE
UpperCaseNameRewriter not implemented

### ISSUE THREAD

**Issue by oakular** [efcore/EFCore.NamingConventions#48]
When trying to add a migration to rename all tables using the snake case format, the following exception is thrown:
`Method 'ProcessForeignKeyOwnershipChanged' in type 'EFCore.NamingConventions.Internal.UpperCaseNameRewriter' from assembly 'EFCore.NamingConventions, Version=1.1.0.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7' does not have an implementation.`

I am using EF Core 5, and noticed you have a PR open for implementing this in 5.0: sorry if I am just stating the obvious here, but thought I'd raise it in case.

**Comment by roji** [comment]
Yeah, you can't mix versions - you'll need to wait until the 5.0 version of EFCore.NamingConventions is released (probably in a day or two).
