### ISSUE TITLE
Migration issue in None-English region machines.

### ISSUE THREAD

**Issue by sbdevman** [efcore/EFCore.NamingConventions#49]
Hi,
There is an issue when using the machine in the Turkish region.
When your application applies migration there is a bug with Turkish characters. for example, it converts customer_id to customer_ıd! 
I am using EF 3.1 in Postgresql

**Comment by YohDeadfall** [comment]
Thanks, will take a look!

**Comment by sbabaei** [comment]
Another problem is in querying! it still uses the " in queries when columns are snake-case but it throws an exception. The below snippet is an example : 

   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)

   at Hellang.Middleware.ProblemDetails.ProblemDetailsMiddleware.Invoke(HttpContext context)

  Exception data:

    Severity: HATA

    SqlState: 42703

    MessageText: p.id sütunu mevcut degil

    Hint: Belki  "p.id" sütununu kullanmak istediniz

    Position: 8

    File: d:\pginstaller_13.auto\postgres.windows-x64\src\backend\parser\parse_relation.c

    Line: 3513

    Routine: errorMissingColumn

**Comment by sbabaei** [comment]
But all of these are happening in using IIS, when I use dotnet run command or exe output to run it works fine. seems that it has a problem with IIS globalization!

**Comment by sbabaei** [comment]
Another Bug! I have an Owned Type that I want to map to the same table as the owner.
This a code snippet of my configuration: 

            builder.OwnsOne<ImportanceDegree>(publication => publication.ImportanceDegree, a =>
            {
                a.Property(x => x.SeverityId).HasColumnName("SeverityId");
            });

When I adding migration I get this error: 

The keys {'Id'} on 'Publication' and {'PublicationId'} on 'ImportanceDegree' are both mapped to 'Publications.Publication.pk_publication' but with different columns ({'Id'} and {'id'}).

**Comment by roji** [comment]
@sbabaei please open a new issue for your second problem (this issue is already about something else), with a full runnable code sample.

**Comment by suadev** [comment]
+1

**Comment by roji** [comment]
Can someone please confirm that this is happening in the 5.0 version of the plugin? The code is passing the invariant culture by default (unless you pass another culture explicitly), so this shouldn't be happening...

If you see this happening in 5.0, a small repro would help...

**Comment by roji** [comment]
Closing for age - there have been fixes around Turkish specifically, so this is probably gone. If the issue still persists in recent versions, please open a new issue with a minimal repro.
