### ISSUE TITLE
Change only particular items

### ISSUE THREAD

**Issue by sbabaei** [efcore/EFCore.NamingConventions#52]
I have a problem in fluent configuration. I set table name and schema names and column names but the lib is changing only foreign keys and indexs names to snake case. Tables, schemas, and columns still Pascal-case.

**Comment by roji** [comment]
@sbabaei can you please submit a runnable code sample?

**Comment by roji** [comment]
Note that if names are set explicitly in model configuration, this library does not override them; it only transforms names that are set by convention.

(one place where this happens is ASP.NET Identity, in case that's where you're seeing issues)

**Comment by roji** [comment]
Closing as no response was provided.
