### ISSUE TITLE
Support for CamelCase naming convention

### ISSUE THREAD

**Issue by fnandocontreras** [efcore/EFCore.NamingConventions#59]
Hello, what about including camelCase in supported naming conventions?
In my case i want to use EF to create and maintain a whole new database schema and this database already use camelCase convention. It would involve only lowercasing the first letter of names.
It's very useful in PostgresSQL to avoid having to use quotes everywhere without needing to lowercase every character.

### Expected behavior:
"FirstName" => "firstName"
"UserDateOfBirth" => "userDateOfBirth"

**Comment by roji** [comment]
We can definitely add that as an additional naming convention - this should be pretty easy to do in case you want to submit a PR.

>  It's very useful in PostgresSQL to avoid having to use quotes everywhere without needing to lowercase every character.

As far as I'm aware, if you don't use quotes then the entire identifier gets lower-cased - so I'm not sure how camelCase would help here. This is one of the advantages of snake_case in PG - since everything is lowercase already, no quotes are needed.

**Comment by fnandocontreras** [comment]
Hi, thanks for your answer, actually i checked-out the code, it seems very simple to add, i 'd like to collaborate and submit a PR, i was just wondering if it would be worst adding new NameRewriter for that or just adding an optional bool parameter to LowerCaseNameRewriter constructor to set wheter to lowercase the whole name or only the first letter.
I understand that the SnakeCase would do the job, but in my usecase am adding a new schema for a database which is already using camelCase. thanks

**Comment by roji** [comment]
I think it makes more sense to have a separate rewriter, since only the first character needs to be lower-cased.

**Comment by fnandocontreras** [comment]
Am getting the following error when pushing to a new branch:
git push --set-upstream origin LowerCaseFirstCharacter
remote: Permission to efcore/EFCore.NamingConventions.git denied to fnandocontreras.
fatal: unable to access 'https://github.com/efcore/EFCore.NamingConventions.git/': The requested URL returned error: 403

do i need some additional rights to be able to push?

**Comment by fnandocontreras** [comment]
It's done, thanks for this

**Comment by roji** [comment]
@fnandocontreras thanks for your contribution!

As this is a small and low-risk feature, I'm including it in the 5.0.2 release which shouldn't be too far off.

**Comment by fnandocontreras** [comment]
thanks for the support, it's been nice to collaborate

**Comment by jsancho** [comment]
> @fnandocontreras thanks for your contribution!
> 
> As this is a small and low-risk feature, I'm including it in the 5.0.2 release which shouldn't be too far off.

Hi @roji , I am unable to find this convention when using the 1.1.0 version of the package.
Would it be possible to have feature parity in both release lines of the packages?

thanks a bunch!

**Comment by roji** [comment]
@jsancho as this is a new feature (and not a bug fix), it's not a normal thing to backport it in general... I also don't really have the time to fully maintain both versions in this way...

**Comment by jsancho** [comment]
Could I submit a PR with the necessary changes?

We are unable to upgrade to 5.0 because the lack of support for Azure Functions :/

**Comment by roji** [comment]
I'm sorry, but I'd really leave old versions where they are apart from bug fixes - it's just standard semver/release policy...

**Comment by roji** [comment]
If it's really critical for you and you're willing to do the work, there's always the possibility of running on a version modified by you until Azure Functions allows 5.0.

**Comment by jsancho** [comment]
Thanks for the suggestion, it's absolutely fair enough for you not to have the time to backport it.

I guess we could be running our own fork, but we've managed to hack a workaround for the time being.
Once either Azure Functions supports 5.0 or 6.0 comes out, we'll be able to get the hack out and bring everything up to latest libs.

The actual disappointment I have is with Azure Functions having been left behind from the general 5.0 release, so we'll just to hold on and wait until our deps can be promoted.
