### ISSUE TITLE
Still uses quoted identifiers with Oracle provider

### ISSUE THREAD

**Issue by dwhaas82** [efcore/EFCore.NamingConventions#61]
I scaffolded a context from an existing Oracle database and I'm trying to get the migrations to not use quoted identifiers.  I followed the example on how to configure and used the ```.UseUpperCaseNamingConvention() ``` but it still uses quoted identifiers in the generated migration scripts.

I am using EFCore 3.1

**Comment by roji** [comment]
@dwhaas82 this plugin doesn't affect how EF Core providers quote identifies - that's up to each specific provider to decide. While the Npgsql PG provider doesn't quote when not necessary, most other providers always quote. All this plugin does is change the identifier names themselves.
