### ISSUE TITLE
Publish nuget version 5.0.4  

### ISSUE THREAD

**Issue by pp-rchekryzhov** [efcore/EFCore.NamingConventions#73]
Atm the published package is based on ef core 5.0.2.
Could you release nuget version 5.0.4, please?

**Comment by roji** [comment]
@pp-rchekryzhov you do not need version 5.0.4 of EFCore.NamingConventions in order to use EF Core 5.0.4. Just add an explicit dependency on the EF Core nuget with the latest patch version.
