### ISSUE TITLE
v5.0.2 UseLowerCaseNamingConvention() does not work on table names with Npgsql provider

### ISSUE THREAD

**Issue by groogiam** [efcore/EFCore.NamingConventions#75]
I have applied the convention using 

```c#
options.UseNpgsql(config.DbPrivilegedConnectionString,
                                opt => opt.MigrationsAssembly(DbMigrationAssemblyNames.PostgreSQL))
                            .UseLowerCaseNamingConvention();
```
I generated a fresh set of migrations to verify it was working and it appears everything but table names are lower cased.

Expected Result: All database identifiers should be lower cased.

**Comment by groogiam** [comment]
Working as expected. I had some hidden configuration messing with my entity name mapping.

**Comment by mjb8086** [comment]
@groogiam Do you remember which configuration caused this problem? I have the same trouble. Everything except the tables is snake cased.

**Comment by groogiam** [comment]
@mjb8086 I think the issue I had was logic in the context OnModelCreating that was looping through the model entity types and setting the names to the ClrTypeName.  E.g. `modelBuilder.Entity(entityType.ClrType).ToTable(entityType.ClrType.Name);`. This was overriding the convention.

**Comment by mjb8086** [comment]
@groogiam Thanks for your reply -  I had a look at my OnModelCreating and suspected this line:

```
modelBuilder.Entity<HbkBaseEntity>().UseTpcMappingStrategy();
```

It's configuring the db to flatten any classes derived from the BaseEntity into single tables. I commented it out but I still see the tables are in Pascal case. I may still have digging to do.
