### ISSUE TITLE
How to config EFCore.NamingConventions when I use services.AddDbContextPool?

### ISSUE THREAD

**Issue by scymen** [efcore/EFCore.NamingConventions#89]
I try to improve the performance, use the `AddDbContextPool` method instead of `AddDbContext` during service registration, then I got an error:
`OnConfiguring' cannot be used to modify DbContextOptions when DbContext pooling is enabled`

same question :
 https://stackoverflow.com/questions/55819175/how-to-use-adddbcontextpool-if-all-configuration-in-onconfiguring-method-of-dbco

Is there anyway to config `EFCore.NamingConventions`  to avoid this error? thanks.

**Comment by roji** [comment]
Have you tried to set up the naming convention in AddDbContextPool?

```c#
services.AddDbContextPool<BlogContext>(o => o
    .UseNpgsql("...")
    .UseSnakeCaseNamingConvention());
```

**Comment by scymen** [comment]
Thanks.
