### ISSUE TITLE
6.0.0-preview.3 stopped working with the release of .NET 6.0 RC1 yesterday

### ISSUE THREAD

**Issue by buvinghausen** [efcore/EFCore.NamingConventions#92]
It was working through preview 7 just fine.

Here is the StackTrace
<pre>
System.TypeLoadException: Method 'GetServiceProviderHashCode' in type 'ExtensionInfo' from assembly 'EFCore.NamingConventions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7' does not have an implementation.
   at EFCore.NamingConventions.Internal.NamingConventionsOptionsExtension.get_Info()
   at Microsoft.EntityFrameworkCore.DbContextOptions.GetHashCode()
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.GetOrAdd(IDbContextOptions options, Boolean providerRequired)
   at Microsoft.EntityFrameworkCore.DbContext..ctor(DbContextOptions options)
</pre>   
Also reverting back to 5.x yields the same exception.

**Comment by buvinghausen** [comment]
Just as a follow on I tried it with an rc1 CI build of 6.0.0-rc.1-ci.20210913T102916 to see if the issue was upstream in Npgsql.EntityFrameworkCore.PostgreSQL and I still get the same exception.

**Comment by ZvonimirMatic** [comment]
EF Core changed the contract for the extensions: https://github.com/dotnet/efcore/issues/26022

Maybe it would be a good idea to upgrade to RC1 version of EF Core?

**Comment by buvinghausen** [comment]
@ZvonimirMatic thank you for the context.  That was why I tried the CI build of Npgsql.EntityFrameworkCore.PostgreSQL is because it is compiled against the RC1 release of EFCore...  Unfortunately it still breaks.

**Comment by buvinghausen** [comment]
[Link](https://github.com/npgsql/efcore.pg/issues/1988)

**Comment by roji** [comment]
Yeah, this is expected - I will be porting the extension to rc1 in the coming weeks...

**Comment by ZvonimirMatic** [comment]
@roji From this PR: https://github.com/dotnet/efcore/pull/26111 it seems to me that the only changes to be made are to make the method `GetServiceProviderHashCode` return `long` instead of `int` and to make method `ShouldUseSameServiceProvider` return `true` (hopefully I didn't oversimplify this). Do you want me to do those changes and create a PR?

**Comment by roji** [comment]
@ZvonimirMatic sure! Hopefully no other changes are needed (as indicated by the OP above)...

**Comment by ZvonimirMatic** [comment]
@roji I created the pull request: https://github.com/efcore/EFCore.NamingConventions/pull/93

A couple of other changes needed to be made. I also updated the version of extension packages, I hope that's all right. All the changes are listed in the PR.

**Comment by buvinghausen** [comment]
@roji I just saw [rc1](https://www.nuget.org/packages/Npgsql.EntityFrameworkCore.PostgreSQL/6.0.0-rc.1) posted to Nuget.  Is there any way we can get this package updated soon since @ZvonimirMatic has the PR ready?

**Comment by roji** [comment]
@buvinghausen I'll be reviewing and merging #93 in the next few days - there's a lot going on at the moment. Thanks for your patience.

**Comment by buvinghausen** [comment]
Thank you Shay

**Comment by thangchung** [comment]
We have got the same issue after upgraded to `.NET v6.0.100-rc.1.21458.32`, and we're looking forward to this merging too.

**Comment by roji** [comment]
@buvinghausen note cd128bbd1342ec13e58137198463e5600ed43abb with some minor fixup to this PR.

**Comment by roji** [comment]
Release 6.0.0-rc.1, thanks @buvinghausen!

**Comment by buvinghausen** [comment]
Thanks @roji everything ran perfectly!

**Comment by roji** [comment]
@buvinghausen great, thanks for confirming and for the PR!

**Comment by buvinghausen** [comment]
@roji I get no take credit for the PR that goes to our main man @ZvonimirMatic

**Comment by roji** [comment]
Oops, sorry... Thanks @ZvonimirMatic !
