### ISSUE TITLE
Another naming convention ( ALL_CAPS )

### ISSUE THREAD

**Issue by Narine-P** [efcore/EFCore.NamingConventions#99]
Hi, 
I have to work with database, where all tables(TABLE_NAME) and columns are like FULL_NAME.
So, is it possible to add naming convention for FullName=>FULL_NAME ? 

I'm using EF CORE 3.1

**Comment by roji** [comment]
Duplicate of #31

**Comment by roji** [comment]
This is already implemented simply do UseUpperSnakeCaseNamingConvention. I'll update the README to make it documented.

**Comment by Narine-P** [comment]
Thank you!
